# Generated by Django 4.1.7 on 2023-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='users_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='users_pic',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, default='', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=55, null=True),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
